#!/bin/bash

clear
echo ""
echo "************************************************************"
echo "WAS "
cat /proc/sys/vm/swappiness
cat /proc/sys/vm/vfs_cache_pressure

# swapoff -a && sudo swapon -a

sysctl -w vm.swappiness=60
sysctl -w vm.vfs_cache_pressure=100

# Сохранить настройку
# sysctl -p

echo ""
echo "NOW !!!"
cat /proc/sys/vm/swappiness
cat /proc/sys/vm/vfs_cache_pressure



echo ""
echo "FREE MEMORY IN MB"
free -m | awk 'NR==3 {print $4 " MB"}'


echo ""
echo "CLEAR CASHE."
/home/arthur/clcc


echo "************************************************************"


